name: hello-itential
type: cli-tool
active: false
status: community
compatibility:
  - platform
description: 👋 Get started with Itential Gateway!
tags:
  - cli
maintainer:
  - William Collins < @wcollins
repo: https://github.com/itential/hello-itential
docs: https://github.com/itential/hello-itential/blob/main/README.md
